// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD51h1E_OrOjfpPXriVShUFM0dSEL_IqfE',
    appId: '1:1010870105010:web:4528b6adad8ebb89466aab',
    messagingSenderId: '1010870105010',
    projectId: 'notification-push-transport',
    authDomain: 'notification-push-transport.firebaseapp.com',
    storageBucket: 'notification-push-transport.firebasestorage.app',
    measurementId: 'G-8NNLLLHHER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDto8jQobjhNCIDsJfLS-LnkvtYtQt_Oas',
    appId: '1:1010870105010:android:cb574209e6f4a985466aab',
    messagingSenderId: '1010870105010',
    projectId: 'notification-push-transport',
    storageBucket: 'notification-push-transport.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTdnErIOz0E_Bv2gyUQaLy5gTLXp4_MdM',
    appId: '1:1010870105010:ios:dd9a35d5e9ee7e7a466aab',
    messagingSenderId: '1010870105010',
    projectId: 'notification-push-transport',
    storageBucket: 'notification-push-transport.firebasestorage.app',
    iosBundleId: 'com.example.maliCompagnie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTdnErIOz0E_Bv2gyUQaLy5gTLXp4_MdM',
    appId: '1:1010870105010:ios:dd9a35d5e9ee7e7a466aab',
    messagingSenderId: '1010870105010',
    projectId: 'notification-push-transport',
    storageBucket: 'notification-push-transport.firebasestorage.app',
    iosBundleId: 'com.example.maliCompagnie',
  );
}
